---

#RHEL7 Ansible Playbook to install a Pulp Master Server
- name: Install deltarpm
  yum: name=deltarpm state=present
  
- name: Install EPEL repo
  yum: name=epel-release state=present

- name: Install Pulp repo
  copy: src=rhel-pulp.repo dest=/etc/yum.repos.d/rhel-pulp.repo
  
- name: Update all rpms to latest
  yum: name=* state=latest

- name: Install All components
  yum: name={{ item }} state=present
  register: event
  with_items:
    - mongodb-server
    - qpid-cpp-server 
    - qpid-cpp-server-store
    - "@pulp-server-qpid"
    - "@pulp-admin"
    - python-crane
    - pulp-docker-plugins
    - pulp-docker-admin-extensions

- name: Ensure auth=no in qpidd.conf
  lineinfile: dest=/etc/qpid/qpidd.conf regexp="^auth=no" line="auth=no"

- name: Copy over crane.conf
  copy: src=crane.conf  dest=/etc/crane.conf

- name: Copy over pulp_docker.conf
  copy: src=pulp_docker.conf dest=/etc/httpd/conf.d/pulp_docker.conf

- name: Copy over rpm.conf
  copy: src=rpm.conf dest=/etc/pulp/vhosts80/rpm.conf
    
- name: Start the services
  service: name={{ item }} state=started enabled=true
  with_items:
    - mongod
    - qpidd
    
- name: initialize pulp db
  shell: sudo -u apache pulp-manage-db
  when: event.changed
  
- name: Start the rest of the services
  service: name={{ item }} state=started enabled=true
  with_items:
    - httpd
    - pulp_workers
    - pulp_celerybeat
    - pulp_resource_manager
